
language: julia
os:
  - linux
julia:
  - 0.4
notifications:
  email: false

script:
  - julia -e 'Pkg.clone(pwd())'
  - julia -e 'Pkg.build("LinearResponseVariationalBayes")'
  - if [ -f test/runtests.jl ]; then julia --check-bounds=yes -e 'Pkg.test("LinearResponseVariationalBayes", coverage=true)'; fi

after_success:
  - julia -e 'cd(Pkg.dir("LinearReponseVariationalBayes")); Pkg.add("Coverage"); using Coverage; Coveralls.submit(Coveralls.process_folder())'
