
language: julia
os:
  - linux
julia:
  - release
notifications:
  email: false

script:
  - if [[ -a .git/shallow ]]; then git fetch --unshallow; fi
  - julia --check-bounds=yes -e 'Pkg.clone(pwd()); Pkg.build("LinearResponseVariationalBayes"); Pkg.test("LinearResponseVariationalBayes"; coverage=true)'

after_success:
  - julia -e 'cd(Pkg.dir("LinearResponseVariationalBayes")); Pkg.add("Coverage"); using Coverage; Coveralls.submit(Coveralls.process_folder())'
